import test from 'node:test';
import assert from 'node:assert/strict';
import {createOrbitalAudio,hearsFlashbang} from '../dist/combat-audio.js';
const point={latitude:42.36,longitude:-71.09,accuracy:4};
function rig(){let at=1000,loc={...point,at};const plays=[],stops=[],audio=createOrbitalAudio({audio:{play:(...a)=>plays.push(a),stop:key=>stops.push(key)},now:()=>at,getLocation:()=>loc});return{audio,plays,stops,time:n=>at=n,location:p=>loc=p};}
const strike=(id='a')=>({id,actorId:'caster',point,radius:10,startsAt:1000,endsAt:6000,victims:[{id:'victim'}]});
test('flashbang sound goes to caster and affected players, not shielded or distant players',()=>{const event={type:'spell',spell:'flashbang',actorId:'caster',affectedIds:['victim'],blockedIds:['shielded']};for(const id of ['caster','victim'])assert.equal(hearsFlashbang(event,id),true);for(const id of ['shielded','distant'])assert.equal(hearsFlashbang(event,id),false);});
test('everyone hears a strike once; late listeners seek to current timestamp',()=>{for(const id of ['caster','victim','spectator']){const r=rig();r.time(2000);r.audio.sync([strike()],id);r.audio.sync([strike()],id);assert.equal(r.plays.length,1);assert.equal(r.plays[0][2].offsetSeconds,1);}});
test('escape stops only this strike, not other audio; stale GPS cannot cancel',()=>{const r=rig();r.audio.sync([strike()],'victim');r.location({latitude:42.361,longitude:-71.09,accuracy:4,at:-10000});r.audio.tick();assert.deepEqual(r.stops,[]);r.location({latitude:42.361,longitude:-71.09,accuracy:4,at:1000});r.audio.tick();assert.deepEqual(r.stops,['orbital:a']);r.audio.sync([strike()],'victim');assert.equal(r.plays.length,1);});
test('caster hears the full strike even outside radius and leaving clears playback',()=>{const r=rig();r.audio.sync([strike()],'caster');r.location({latitude:42.361,longitude:-71.09,accuracy:4,at:1000});r.audio.tick();assert.deepEqual(r.stops,[]);r.audio.clear();assert.ok(r.stops.includes('orbital:a'));});
test('an outside listener stops after entering and then escaping, expired strikes never restart',()=>{const r=rig();r.location({latitude:42.361,longitude:-71.09,accuracy:4,at:1000});r.audio.sync([strike()],'outside');assert.equal(r.plays.length,1);r.location({...point,at:1000});r.audio.tick();r.location({latitude:42.361,longitude:-71.09,accuracy:4,at:1000});r.audio.tick();assert.ok(r.stops.includes('orbital:a'));r.time(7000);r.audio.sync([strike('expired')],'outside');assert.equal(r.plays.length,1);});
