import test from 'node:test';import assert from 'node:assert/strict';
import {createScoreStore} from '../server/scores.js';import {freshLoadout,attacksFor,ruleFor,wordsFor,skillName} from '../dist/economy.js';import {launchProjectile,impactProjectile,castSpell,settleRoom} from '../dist/rules.js';import {spawnPlayer,advanceRespawns,requestRespawn} from '../dist/respawn.js';import {launchOrbital,resolveOrbitals,rememberOrbitalLocation} from '../server/orbital.js';import {creditContinuous} from '../server/continuous-scores.js';import {spellsFromText} from '../dist/voice.js';import {createBoxMotion} from '../dist/box-motion.js';import {createFaceSearch} from '../dist/face-search.js';
const make=(id,persona='mage')=>{const p={id,name:id,persona,economy:true,loadout:freshLoadout(),faceReady:true,connected:true};spawnPlayer(p,1000);return p;};
const arena=()=>({economy:true,enhanced:true,continuous:true,phase:'playing',eventRound:{mode:'ffa'},players:[make('a'),make('b')],shots:[]});
test('shop enforces balance, consecutive unlocks, one upgrade, and preserves purchases across character changes',()=>{const s=createScoreStore(null,{ranking:'coins'}),p=s.register('A');assert.ok(s.purchase(p.id,'mage','unlock','fireball').error);s.award(p.id,0,0,0,true,400);assert.ok(s.purchase(p.id,'mage','unlock','meteor').error);assert.ok(s.purchase(p.id,'mage','unlock','bombArrow').error);assert.equal(s.purchase(p.id,'mage','unlock','fireball').coins,340);assert.ok(s.purchase(p.id,'mage','unlock','fireball').error);assert.equal(s.purchase(p.id,'mage','upgrade','lightning').coins,260);assert.ok(s.purchase(p.id,'mage','upgrade','lightning').error);assert.equal(s.purchase(p.id,'mage','unlock','meteor').coins,120);assert.equal(s.purchase(p.id,'witch','consumable','heal').coins,90);assert.equal(s.loadout(p.id).skills.lightning,2);assert.equal(s.loadout(p.id).consumables.heal,1);assert.ok(s.purchase(p.id,'mage','consumable','__proto__').error);});
test('each class begins with only quick attack; upgrades raise damage but never reduce delay; no automatic supers',()=>{for(const persona of ['mage','witch','archer']){const r=arena(),p=r.players[0];p.persona=persona;const [quick,heavy,ultimate]=attacksFor(persona);assert.equal(p.health,70);assert.equal(p.loadout.skills[quick],1);assert.ok(launchProjectile(r,'a',heavy,'b','locked',1000).error);assert.ok(launchProjectile(r,'a',ultimate,'b','locked2',1000).error);const before=ruleFor(p,quick);p.loadout.skills[quick]=2;const after=ruleFor(p,quick);assert.ok(after.damage>before.damage);assert.equal(after.cooldown,before.cooldown);for(let i=0;i<4;i++){p.mana=10;const shot=launchProjectile(r,'a',quick,'b','s'+i,1000+i*2000);assert.equal(shot.error,undefined);assert.equal(shot.super,undefined);assert.equal(shot.upgraded,true);}assert.deepEqual(p.castCounts,{});}});
test('ultimates require full mana, deal near-lethal damage, and preserve a half-heart or more',()=>{for(const persona of ['mage','witch','archer']){const r=arena(),p=r.players[0],id=attacksFor(persona)[2];p.persona=persona;p.loadout.skills[id]=1;p.mana=9;p.manaUpdatedAt=1000;assert.ok(launchProjectile(r,'a',id,'b','no',1000).error);p.mana=10;const shot=launchProjectile(r,'a',id,'b','yes',1000);assert.equal(p.mana,0);assert.equal(shot.attackRule.damage,60);const hit=impactProjectile(r,'a',shot.shotId,true,shot.impactAt);assert.equal(hit.blocked,false);assert.equal(r.players[1].health,10);}});
test('consumables consume one stock only on success; shield blocks all spells except lightning, including flashbang',()=>{for(const id of ['fireball','poison','skeletonArmy','arrows','meteor','soulReaper','bombArrow','ballista','lightning']){const r=arena(),[a,b]=r.players;const persona=['mage','witch','archer'].find(p=>attacksFor(p).includes(id));a.persona=persona||'mage';a.loadout.skills[id]=1;a.loadout.consumables.flashbang=1;b.loadout.consumables.shield=1;b.poison={by:'a',startedAt:1000,until:5000,perSecond:2,applied:0};castSpell(r,'b','shield',null,1000);assert.equal(b.shieldUntil,8000);assert.equal(b.poison,null);assert.equal(b.loadout.consumables.shield,0);assert.ok(castSpell(r,'b','shield',null,1100).error);const shot=launchProjectile(r,'a',id,'b','hit',1500);assert.equal(shot.error,undefined,id);const hit=impactProjectile(r,'a','hit',true,shot.impactAt);assert.equal(hit.blocked,id!=='lightning',id);assert.equal(b.health,id==='lightning'?60:70,id);assert.equal(b.flashUntil,0);}
const r=arena(),a=r.players[0];a.health=30;a.loadout.consumables.heal=1;castSpell(r,'a','heal',null,1000);assert.equal(a.health,70);assert.equal(a.loadout.consumables.heal,0);});
test('death shop waits for manual respawn and non-FFA cannot respawn',()=>{const r=arena(),p=r.players[0];p.health=0;p.loadout.skills.fireball=2;advanceRespawns(r,2000);assert.ok(requestRespawn(r,p,11999).error);advanceRespawns(r,13000);assert.equal(p.health,0);assert.deepEqual(requestRespawn(r,p,13000),{});assert.equal(p.health,70);assert.equal(p.loadout.skills.fireball,2);assert.equal(p.life,2);p.health=0;p.respawnAt=10000;r.eventRound.mode='koth';assert.ok(requestRespawn(r,p,14000).error);});
test('orbital warns for 5 seconds in 25m, allows actions and escape, catches entrants, and spares caster',()=>{
 const r=arena(),[a,b]=r.players,c=make('c');r.players.push(c);for(const p of r.players)p.location={latitude:42,longitude:-71,accuracy:2,at:1000};c.location.latitude+=.0003;a.airstrikeCharges=1;b.shieldUntil=10000;
 launchProjectile(r,'a','lightning','b','flight',1000);const result=launchOrbital(r,a,{latitude:42,longitude:-71},1000);assert.equal(result.strike.radius,25);assert.equal(result.strike.endsAt,6000);assert.deepEqual(result.strike.victims.map(v=>v.id),['b']);assert.equal(r.shots.length,1);assert.equal(a.airstrikeCharges,0);
 assert.equal(launchProjectile(r,'b','lightning','a','allowed',2000).error,undefined);assert.ok(launchOrbital(r,a,a.location,2000).error);
 b.location={...c.location,at:3500};c.location={...a.location,at:3500};c.shieldUntil=10000;
 assert.equal(resolveOrbitals(r,5999).length,0);const hits=resolveOrbitals(r,6000);assert.equal(hits.length,1);assert.equal(hits[0].targetId,c.id);assert.equal(b.health,70);assert.equal(a.health,70);assert.equal(c.health,0);assert.deepEqual(resolveOrbitals(r,6000),[]);
});
test('disconnect cannot erase a strike, but a recorded escape remains safe',()=>{
 for(const escaped of [false,true]){const r=arena(),[a,b]=r.players;for(const p of r.players)p.location={latitude:42,longitude:-71,accuracy:2,at:1000};a.airstrikeCharges=1;launchOrbital(r,a,a.location,1000);if(escaped)b.location.latitude+=.0003;rememberOrbitalLocation(r,b);b.location=null;b.connected=false;b.faceReady=false;resolveOrbitals(r,6000);assert.equal(b.health,escaped?70:0);}
});
test('orbital ignores stale fixes and draws a rising then falling 3D arc',async()=>{
 const {rocketPath,rocketMapPath,inOrbitalZone}=await import('../dist/orbital-rules.js');const a=rocketPath(0),b=rocketPath(.5),c=rocketPath(1);assert.ok(b.position[1]>a.position[1]&&b.position[1]>c.position[1]);assert.ok(b.position[0]!==a.position[0]);assert.ok(c.position[2]>b.position[2]);assert.ok(a.tangent[1]>0&&c.tangent[1]<0);const mapEnd=rocketMapPath(1,.6,{x:.5,y:.5});assert.deepEqual(mapEnd.position,[0,0,-7]);assert.ok(rocketMapPath(0).position[1]>mapEnd.position[1]);assert.ok(rocketMapPath(1).tangent[1]<0);assert.equal(inOrbitalZone({point:{latitude:42,longitude:-71}}, {latitude:42,longitude:-71,accuracy:1,at:0},11000),false);
});
test('orbital rejects stale GPS/invalid coordinates and round end cancels deaths',()=>{const r=arena(),a=r.players[0];a.airstrikeCharges=1;a.location={latitude:42,longitude:-71,at:0};assert.ok(launchOrbital(r,a,a.location,11001).error);assert.ok(launchOrbital(r,a,{latitude:999,longitude:0},1000).error);a.location.at=1000;r.players[1].location={...a.location};assert.equal(launchOrbital(r,a,a.location,1000).error,undefined);r.phase='finished';assert.deepEqual(resolveOrbitals(r,6000),[]);assert.equal(r.players[1].health,70);});
test('paid names and forgiving commands map once to owned skills; locked skills cannot be cast',()=>{const p=make('a');p.loadout.skills.fireball=2;p.loadout.skills.meteor=1;p.loadout.consumables={heal:1,shield:1,flashbang:1};const words=wordsFor(p);assert.equal(skillName(p,'fireball'),'Wildfire');assert.deepEqual(spellsFromText('wild fire heel flash bank meteorr',words),['fireball','heal','flashbang','meteor']);assert.deepEqual(spellsFromText('fleshbang sheild chain lighting',words),['flashbang','shield','lightning']);assert.deepEqual(spellsFromText('arrows',words),[]);assert.deepEqual(spellsFromText('fire',words),[]);});
test('visual box smoothing moves between sparse detections, converges, and resets immediately on identity change',()=>{const m=createBoxMotion(),a={x:.2,y:.2,width:.1,height:.12},b={...a,x:.24};assert.deepEqual(m.sample(a,'a',0),a);const one=m.sample(b,'a',16),two=m.sample(b,'a',32);assert.ok(one.x>.2&&one.x<.24);assert.ok(two.x>one.x&&two.x<.24);let end;for(let t=48;t<300;t+=16)end=m.sample(b,'a',t);assert.ok(Math.abs(end.x-.24)<.002);assert.deepEqual(m.sample(a,'b',300),a);assert.deepEqual(b,{x:.24,y:.2,width:.1,height:.12});m.reset();assert.deepEqual(m.sample(b,'a',310),b);});
test('slow face tracking gives follow crops priority but still searches the full scene',()=>{const search=createFaceSearch(),args={width:1280,height:720,point:{x:640,y:300},follow:[{x:520,y:200,width:260,height:260}],budgetMs:400};search.next({...args,at:0});assert.equal(search.next({...args,at:800}).some(r=>r.full),false);assert.equal(search.next({...args,at:1700}).some(r=>r.full),true);});

test('airstrike hold gesture distinguishes tap, movement, cancellation and one stationary launch',async t=>{const {createHoldGesture}=await import('../dist/hold-gesture.js');t.mock.timers.enable({apis:['setTimeout']});let count=0;const h=createHoldGesture({onHold:()=>count++});h.begin({x:10,y:10});t.mock.timers.tick(100);h.cancel();t.mock.timers.tick(1000);assert.equal(count,0);h.begin({x:10,y:10});t.mock.timers.tick(500);h.move({x:30,y:10});t.mock.timers.tick(1000);assert.equal(count,0);h.begin({x:10,y:10});t.mock.timers.tick(799);assert.equal(count,0);t.mock.timers.tick(1);assert.equal(count,1);t.mock.timers.tick(2000);assert.equal(count,1);h.begin({x:10,y:10});h.cancel();t.mock.timers.tick(900);assert.equal(count,1);});
test('seven-heart passive regeneration is half a heart per eight seconds and never revives',()=>{const r=arena(),a=r.players[0];a.health=60;settleRoom(r,8999);assert.equal(a.health,60);settleRoom(r,9000);assert.equal(a.health,65);settleRoom(r,17000);assert.equal(a.health,70);a.health=0;settleRoom(r,25000);assert.equal(a.health,0);});

test('orbital 25m boundary includes players at 24m and excludes players at 26m',async()=>{
 const {inOrbitalZone,ORBITAL}=await import('../dist/orbital-rules.js');assert.equal(ORBITAL.radius,25);
 const r=arena(),a=r.players[0],b=r.players[1],c=make('outside');r.players.push(c);
 const loc=metres=>({latitude:42+metres/111195,longitude:-71,accuracy:1,at:1000});a.location=loc(0);b.location=loc(24);c.location=loc(26);a.airstrikeCharges=1;
 const {strike}=launchOrbital(r,a,a.location,1000);assert.deepEqual(strike.victims.map(p=>p.id),[b.id]);
 assert.equal(inOrbitalZone(strike,b.location,1000),true);assert.equal(inOrbitalZone(strike,c.location,1000),false);
 resolveOrbitals(r,6000);assert.equal(b.health,0);assert.equal(c.health,70);assert.equal(a.health,70);
});
