import {COINS_PER_KILL,UNLOCK_COST,UPGRADE_COST,CONSUMABLES} from '../dist/economy.js';
const spent=UNLOCK_COST[1]+UPGRADE_COST[0]+CONSUMABLES.heal.cost;
import test from 'node:test';import assert from 'node:assert/strict';import {WebSocket} from 'ws';import {createGameServer} from '../server/index.js';import {encodeDescriptor,DESCRIPTOR_LENGTH} from '../dist/face-id.js';
const face=[encodeDescriptor(Array.from({length:DESCRIPTOR_LENGTH},()=>1/Math.sqrt(DESCRIPTOR_LENGTH)))];
test('real clients earn coins, buy while dead, keep purchases after reconnect, and launch one server-authorized airstrike',async t=>{
 const game=createGameServer({continuous:true,respawnDelayMs:30});await new Promise(r=>game.server.listen(0,'127.0.0.1',r));t.after(()=>game.close());const base=`http://127.0.0.1:${game.server.address().port}`;
 async function client(name,token){const ws=new WebSocket(base.replace('http:','ws:')+'/ws'),messages=[];t.after(()=>ws.terminate());ws.on('message',raw=>messages.push(JSON.parse(raw)));await new Promise(r=>ws.on('open',r));const send=m=>ws.send(JSON.stringify(m));const timer=setInterval(()=>{if(ws.readyState===1)send({type:'ping',at:Date.now()});},2000);t.after(()=>clearInterval(timer));const next=async(type,predicate=()=>true)=>{for(let n=0;n<500;n++){const i=messages.findIndex(m=>m.type===type&&predicate(m));if(i>=0)return messages.splice(i,1)[0];await new Promise(r=>setTimeout(r,5));}throw Error('No '+type+' '+name);};send({type:'join',name,token});const welcome=await next('welcome');return{...welcome,ws,send,next,messages};}
 const a=await client('Coin Alice'),b=await client('Coin Bob');for(const p of [a,b])p.send({type:'face',samples:face});await a.next('state',m=>m.room.players.every(p=>p.faceReady));const board=async()=>(await(await fetch(base+'/api/leaderboard')).json()).players;const room=game.rooms.get('ARENA'),alice=room.players.find(p=>p.id===a.id),bob=room.players.find(p=>p.id===b.id);assert.equal(room.eventRound.mode,'ffa');assert.equal(alice.health,70);
 a.send({type:'purchase',kind:'unlock',item:'fireball'});assert.match((await a.next('error')).message,/Shop/);a.send({type:'cast',spell:'meteor',targetId:b.id});assert.match((await a.next('error')).message,/Unlock/);
 for(let i=0;i<5;i++){bob.health=10;alice.cooldowns={};alice.mana=10;a.send({type:'cast',spell:'lightning',targetId:b.id});const shot=await a.next('spell',m=>m.actorId===a.id);a.send({type:'impact',shotId:shot.shotId,tracked:true});await a.next('arena-event',m=>m.kind==='kill');assert.equal((await board()).find(p=>p.id===a.id).coins,(i+1)*COINS_PER_KILL);const dead=await b.next('state',m=>m.room.players.find(p=>p.id===b.id)?.respawnAt>0);await new Promise(r=>setTimeout(r,40));b.send({type:'respawn'});await b.next('state',m=>m.room.players.find(p=>p.id===b.id)?.life===i+2);}
 assert.equal(alice.airstrikeCharges,1);assert.equal((await board()).find(p=>p.id===a.id).coins,5*COINS_PER_KILL);
 for(const p of [a,b])p.send({type:'location',location:{latitude:42.36,longitude:-71.09,accuracy:2}});await a.next('state',m=>m.room.players.every(p=>p.location));a.send({type:'orbital',point:{latitude:42.36,longitude:-71.09}});const strike=await a.next('orbital');assert.deepEqual(strike.strike.victims.map(v=>v.id),[b.id]);a.send({type:'orbital',point:{latitude:42.36,longitude:-71.09}});assert.match((await a.next('error')).message,/five-kill/);b.send({type:'cast',spell:'lightning',targetId:a.id});assert.equal((await b.next('spell',m=>m.actorId===b.id)).spell,'lightning');
 // Advance the server-owned timer only; closing the tab must not erase a still-inside last fix.
 b.send({type:'inactive'});await a.next('state',m=>m.room.players.length===1);room.airstrikes[0].endsAt=Date.now()-1;await a.next('arena-event',m=>m.kind==='kill'&&m.victim==='Coin Bob');assert.equal(alice.health,70);assert.equal(bob.health,0);assert.equal((await board()).find(p=>p.id===a.id).coins,6*COINS_PER_KILL);assert.equal((await board()).find(p=>p.id===b.id).deaths,6);
 alice.health=0;alice.actionLockUntil=0;await a.next('state',m=>m.room.players.find(p=>p.id===a.id)?.respawnAt>0);a.send({type:'purchase',kind:'unlock',item:'fireball'});await a.next('state',m=>m.room.players.find(p=>p.id===a.id)?.loadout.skills.fireball===1);a.send({type:'purchase',kind:'upgrade',item:'lightning'});await a.next('state',m=>m.room.players.find(p=>p.id===a.id)?.loadout.skills.lightning===2);a.send({type:'purchase',kind:'consumable',item:'heal'});const bought=await a.next('state',m=>m.room.players.find(p=>p.id===a.id)?.loadout.consumables.heal===1);assert.equal(bought.room.players.find(p=>p.id===a.id).score.coins,6*COINS_PER_KILL-spent);
 a.send({type:'inactive'});await new Promise(r=>a.ws.once('close',r));const again=await client('Coin Alice',a.token);again.send({type:'face',samples:face});await again.next('state',m=>m.room.players.find(p=>p.id===a.id)?.faceReady);again.send({type:'respawn'});const returned=await again.next('state',m=>m.room.players.find(p=>p.id===a.id)?.health===70);const own=returned.room.players.find(p=>p.id===a.id);assert.equal(own.score.coins,6*COINS_PER_KILL-spent);assert.equal(own.loadout.skills.lightning,2);assert.equal(own.loadout.skills.fireball,1);assert.equal(own.loadout.consumables.heal,1);const live=await(await fetch(base+'/api/live')).json();assert.equal(live.players[0].coins,6*COINS_PER_KILL-spent);assert.ok(!JSON.stringify(live).includes('trophies'));assert.ok(!JSON.stringify(live).includes('loadout'));assert.ok(!JSON.stringify(live.players).includes('latitude'));assert.ok(Array.isArray(live.map.players));assert.ok(live.map.casts.some(c=>c.kind==='orbital'&&c.radius===10&&c.to.latitude===42.36));assert.ok(!JSON.stringify(live.map).includes('samples'));assert.ok(!JSON.stringify(live.map).includes('token'));
});
