import {COINS_PER_KILL} from '../dist/economy.js';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createScoreStore} from '../server/scores.js';import {creditContinuous} from '../server/continuous-scores.js';import {createEventRounds,KOTH_MS} from '../server/event-rounds.js';import {spawnPlayer,advanceRespawns,selectRespawnPersona} from '../dist/respawn.js';import {launchProjectile,impactProjectile,castSpell,settle,manaAt} from '../dist/rules.js';import {targetMask,damageForMe} from '../dist/damage-mask.js';import {createGameServer} from '../server/index.js';
const players=()=>['a','b'].map(id=>{const p={id,name:id,connected:true,faceReady:true};spawnPlayer(p,1000);return p;});
const arena=()=>({continuous:true,enhanced:true,phase:'playing',endsAt:0,players:players(),shots:[]});
test('coins reward a kill once per life and persist with identity; old trophies are not public',()=>{
 const dir=mkdtempSync(join(tmpdir(),'clash-coins-')),file=join(dir,'board.json');try{const s=createScoreStore(file,{ranking:'coins'}),a={...s.register('A'),health:70,life:1},b={...s.register('B'),health:0,life:1},room={players:[a,b]};assert.equal(s.standings()[0].coins,0);const event={actorId:a.id,targetId:b.id,amount:25,lethal:true};creditContinuous(room,s,event);creditContinuous(room,s,event);assert.deepEqual(s.standings().map(p=>p.coins),[COINS_PER_KILL,0]);const restart=createScoreStore(file,{ranking:'coins'});assert.equal(restart.find(a.token).id,a.id);assert.equal(restart.standings()[0].coins,COINS_PER_KILL);assert.equal('trophies' in restart.standings()[0],false);
 const old=JSON.parse(readFileSync(file));delete old.players[0].coins;old.players[0].trophies=800;writeFileSync(file,JSON.stringify(old));assert.equal(createScoreStore(file).standings().find(p=>p.id===a.id).coins,0);
 }finally{rmSync(dir,{recursive:true});}
});
test('third accepted cast is super; failed casts do not advance and respawn clears charge',()=>{const r=arena(),a=r.players[0];for(let i=0;i<3;i++){a.mana=10;const shot=launchProjectile(r,'a','fireball','b','s'+i,1000+i*2000);assert.equal(!!shot.super,i===2);assert.ok(launchProjectile(r,'a','fireball','b','bad'+i,1001+i*2000).error);if(i===2){const hit=impactProjectile(r,'a',shot.shotId,true,shot.impactAt);assert.equal(hit.super,true);assert.equal(r.players[1].health,60);}}assert.equal(a.castCounts.fireball,0);assert.equal(a.castCounts.lightning,undefined);spawnPlayer(a,10000);assert.deepEqual(a.castCounts,{});});
test('parry reflects once with the defender as caster and does not reflect lightning',()=>{const r=arena(),[a,b]=r.players;const shot=launchProjectile(r,'a','fireball','b','s',1000);castSpell(r,'b','shield',null,2300);const hit=impactProjectile(r,'a','s',true,2400);assert.equal(hit.parried,true);assert.equal(b.health,100);assert.equal(hit.reflection.actorId,'b');castSpell(r,'a','shield',null,2700);const returned=impactProjectile(r,'b',hit.reflection.shotId,true,2850);assert.equal(returned.blocked,true);assert.equal(returned.parried,undefined);assert.equal(r.shots.length,0);a.mana=10;const lightning=launchProjectile(r,'a','lightning','b','l',2900);assert.equal(impactProjectile(r,'a','l',true,lightning.impactAt).blocked,false);});
test('Aegis clears lingering damage and blocks zap but still lets lightning through',()=>{const r=arena(),[a,b]=r.players;a.persona='archer';b.castCounts={shield:2};b.poison={};b.swarm={};castSpell(r,'b','shield',null,1000);assert.equal(b.poison,null);assert.equal(b.swarm,null);const shot=launchProjectile(r,'a','zap','b','z',1500);assert.equal(impactProjectile(r,'a','z',true,shot.impactAt).blocked,true);a.persona='mage';a.mana=10;const bolt=launchProjectile(r,'a','lightning','b','l',2000);assert.equal(impactProjectile(r,'a','l',true,bolt.impactAt).blocked,false);});
test('Renewal handles late ticks without resurrecting someone killed before the first heal',()=>{const p=players()[0];p.health=2;p.renewal={at:1000,until:6000};p.poison={by:'b',startedAt:1000,until:6000,applied:0,perSecond:3};settle(p,6000);assert.equal(p.health,0);const q=players()[0];q.health=50;q.renewal={at:1000,until:6000};settle(q,6000);assert.equal(q.health,65);});
test('KOTH accounts crown time, transfers on kills, ends at three minutes and FFA restarts',()=>{const r=arena(),events=[],rounds=createEventRounds({random:()=>0,announce:(_,e)=>events.push(e)});assert.deepEqual(rounds.start(r,'koth',1000),{});assert.equal(r.eventRound.kingId,'a');rounds.tick(r,11000);r.players[0].health=0;rounds.kill(r,{actorId:'b',targetId:'a'},11000);assert.equal(r.eventRound.kingId,'b');assert.equal(r.eventRound.players.a.heldMs,10000);rounds.tick(r,1000+KOTH_MS+1000);assert.equal(r.phase,'finished');assert.equal(r.results.winnerId,'b');assert.equal(r.results.players[0].heldMs,170000);assert.equal(events.at(-1).kind,'round-end');rounds.start(r,'ffa',200000);assert.equal(r.endsAt,0);assert.equal(r.players[0].health,100);assert.equal(r.eventRound.mode,'ffa');rounds.manaSurge(r,200000);r.players[0].mana=0;assert.equal(manaAt(r.players[0],203000),4);rounds.end(r,203000);assert.equal(r.players[0].manaBoostUntil,0);});
test('KOTH cannot start with one player and disconnect stops crown time at handoff',()=>{const r=arena(),rounds=createEventRounds({random:()=>0});r.players[1].connected=false;assert.ok(rounds.start(r,'koth',1000).error);r.players[1].connected=true;rounds.start(r,'koth',1000);rounds.account(r,6000);r.players[0].connected=false;rounds.tick(r,6000);rounds.tick(r,10000);assert.equal(r.eventRound.players.a.heldMs,5000);assert.equal(r.eventRound.players.b.heldMs,4000);});
test('damage mask keeps target component at 50% alpha, excludes disconnected bystander and ignores misses',()=>{const values=new Float32Array(36);for(const i of [7,8,13,14,19,20,10,16,22])values[i]=1;const mask=targetMask(values,6,6,{x:1,y:1,width:2,height:1});assert.equal(mask[7*4+3],128);assert.equal(mask[19*4+3],128);assert.equal(mask[10*4+3],0);assert.equal(mask[0],0);assert.equal(damageForMe({type:'impact',actorId:'a',targetId:'b',amount:20},'a'),false);assert.equal(damageForMe({type:'damage',actorId:'a',targetId:'b',amount:20},'a'),true);assert.equal(damageForMe({type:'damage',actorId:'b',targetId:'a',amount:20},'a'),false);assert.equal(damageForMe({type:'damage',actorId:'a',targetId:'b',amount:0},'a'),false);});
test('admin requires password and same-origin session; start/end broadcast, no credentials in public state',async t=>{const game=createGameServer({continuous:true,adminPassword:'test-only-secret'});await new Promise(r=>game.server.listen(0,'127.0.0.1',r));t.after(()=>game.close());const base=`http://127.0.0.1:${game.server.address().port}`,request=(path,body,cookie,origin)=>fetch(base+'/api/admin/'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(cookie?{cookie}:{}),...(origin?{origin}:{})},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await request('state')).status,401);assert.equal((await request('login',{password:'wrong'})).status,401);const login=await request('login',{password:'test-only-secret'});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert.match(cookie,/HttpOnly; SameSite=Strict/);assert.equal((await request('command',{action:'end'},cookie,'https://untrusted.invalid')).status,403);assert.equal((await request('command',{action:'end'})).status,401);assert.equal((await request('command',{action:'start',mode:'ffa'},cookie)).status,200);assert.equal((await request('command',{action:'end'},cookie)).status,200);let live=await(await fetch(base+'/api/live')).json();assert.equal(live.round.phase,'finished');assert.deepEqual(live.events.slice(0,2).map(e=>e.kind),['round-end','round-start']);assert.ok(!JSON.stringify(live).includes('test-only-secret'));await request('logout',{},cookie);assert.equal((await request('state',null,cookie)).status,401);});

test('FFA character choice changes the respawn deck without changing deadline or restoring health early',()=>{const r=arena(),p=r.players[0];p.health=0;advanceRespawns(r,2000,10000);const at=p.respawnAt;assert.deepEqual(selectRespawnPersona(r,p,'witch',3000),{});assert.equal(p.health,0);assert.equal(p.persona,undefined);assert.equal(p.respawnAt,at);assert.ok(selectRespawnPersona(r,p,'constructor',4000).error);advanceRespawns(r,at-1);assert.equal(p.health,0);advanceRespawns(r,at);assert.equal(p.persona,'witch');assert.equal(p.health,100);assert.equal(p.nextPersona,undefined);assert.ok(selectRespawnPersona(r,p,'archer',at+1).error);});
test('non-FFA death cannot respawn or change character, including after reconnect',()=>{const r=arena(),p=r.players[0],rounds=createEventRounds({random:()=>0});rounds.start(r,'koth',1000);p.health=0;p.respawnAt=2000;p.connected=false;advanceRespawns(r,15000);assert.equal(p.health,0);p.connected=true;advanceRespawns(r,15001);assert.equal(p.health,0);assert.ok(selectRespawnPersona(r,p,'witch',15001).error);rounds.start(r,'ffa',16000);assert.equal(p.health,100);assert.equal(p.respawnAt,null);});
