import test from 'node:test';import assert from 'node:assert/strict';import {WebSocket} from 'ws';
import {createGameServer} from '../server/index.js';import {encodeDescriptor,DESCRIPTOR_LENGTH} from '../dist/face-id.js';
const face=[encodeDescriptor(Array.from({length:DESCRIPTOR_LENGTH},()=>1/Math.sqrt(DESCRIPTOR_LENGTH)))];
test('server enforces FFA countdown choice, confirms attacker-only damage, and KOTH elimination survives reconnect',async t=>{
 const game=createGameServer({continuous:true,adminPassword:'test-secret',respawnDelayMs:500});await new Promise(r=>game.server.listen(0,'127.0.0.1',r));t.after(()=>game.close());const base=`http://127.0.0.1:${game.server.address().port}`;
 async function client(name,token){const ws=new WebSocket(base.replace('http:','ws:')+'/ws'),messages=[];t.after(()=>ws.terminate());ws.on('message',raw=>messages.push(JSON.parse(raw)));await new Promise(r=>ws.on('open',r));const send=m=>ws.send(JSON.stringify(m));const next=async(type,predicate=()=>true)=>{for(let n=0;n<400;n++){const i=messages.findIndex(m=>m.type===type&&predicate(m));if(i>=0)return messages.splice(i,1)[0];await new Promise(r=>setTimeout(r,10));}throw Error('No '+type);};send({type:'join',name,token});const welcome=await next('welcome');return{...welcome,ws,send,next,messages};}
 const a=await client('Alice'),b=await client('Bob');for(const c of [a,b])c.send({type:'face',samples:face});await a.next('state',m=>m.room.players.every(p=>p.faceReady));const room=game.rooms.get('ARENA');a.send({type:'persona',persona:'witch'});assert.match((await a.next('error')).message,/respawn countdown/);
 room.players.find(p=>p.id===b.id).health=10;a.send({type:'cast',spell:'lightning',targetId:b.id});const shot=await a.next('spell');a.send({type:'impact',shotId:shot.shotId,tracked:true});const damage=await a.next('damage');assert.equal(damage.targetId,b.id);assert.equal(damage.amount,10);assert.equal(b.messages.filter(m=>m.type==='damage').length,0);
 const dead=await b.next('state',m=>m.room.players.find(p=>p.id===b.id).respawnAt>0),deadline=dead.room.players.find(p=>p.id===b.id).respawnAt;b.send({type:'persona',persona:'witch'});const chosen=await b.next('state',m=>m.room.players.find(p=>p.id===b.id).nextPersona==='witch');assert.equal(chosen.room.players.find(p=>p.id===b.id).respawnAt,deadline);await new Promise(r=>setTimeout(r,550));b.send({type:'respawn'});const respawn=await b.next('state',m=>m.room.players.find(p=>p.id===b.id).life===2);assert.equal(respawn.room.players.find(p=>p.id===b.id).persona,'witch');
 const login=await fetch(base+'/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:'test-secret'})});const cookie=login.headers.get('set-cookie');const start=await fetch(base+'/api/admin/command',{method:'POST',headers:{'content-type':'application/json',cookie},body:JSON.stringify({action:'start',mode:'koth'})});assert.equal(start.status,200);await b.next('state',m=>m.room.eventRound.mode==='koth');room.players.find(p=>p.id===b.id).health=10;a.send({type:'cast',spell:'lightning',targetId:b.id});const second=await a.next('spell',m=>m.shotId!==shot.shotId);a.send({type:'impact',shotId:second.shotId,tracked:true});const out=await b.next('state',m=>m.room.players.find(p=>p.id===b.id).eliminated);assert.equal(out.room.players.find(p=>p.id===b.id).respawnAt,null);b.send({type:'persona',persona:'archer'});assert.match((await b.next('error')).message,/FFA/);
 const closed=new Promise(r=>b.ws.once('close',r));b.ws.close();await closed;const again=await client('Bob',b.token);const stillOut=await again.next('state');assert.equal(stillOut.room.players.find(p=>p.id===b.id).health,0);await new Promise(r=>setTimeout(r,600));assert.equal(room.players.find(p=>p.id===b.id).health,0);assert.equal(room.players.find(p=>p.id===b.id).respawnAt,null);
});
