import test from 'node:test';import assert from 'node:assert/strict';import {access} from 'node:fs/promises';
import {createSpellAudio} from '../dist/sound.js';import {MEME_CLIPS,soundCues} from '../dist/meme-sounds.js';import {SPELLS} from '../dist/rules.js';
function rig(fetchOverride){const starts=[],stops=[];const node=()=>({connect(x){return x;},disconnect(){}});class Context{constructor(){this.state='running';this.currentTime=0;this.destination=node();}createGain(){return{...node(),gain:{value:1}};}decodeAudioData(){return Promise.resolve({numberOfChannels:1,length:400,sampleRate:100,duration:4,getChannelData:()=>new Float32Array(400).fill(.5)});}createBufferSource(){return{...node(),playbackRate:{value:1},start(...args){starts.push(args);},stop(){stops.push(1);}};}}
 const audio=createSpellAudio({Context:()=>Context,fetchAudio:fetchOverride||(()=>Promise.resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(8)})),random:()=>.5});return{audio,starts,stops};}
test('all normal and super spells resolve to bundled attributed clips',async()=>{for(const spell of Object.keys(SPELLS))for(const kind of ['cast','super','impact']){const cues=soundCues(spell,kind);assert.ok(cues.length);for(const c of cues){assert.ok(MEME_CLIPS[c.clip]?.source);await access(new URL(`../dist/media/memes/${c.clip}.mp3`,import.meta.url));}}});
test('recorded clips play after unlock; volume mute and stop apply to all sources',async()=>{const{audio,starts,stops}=rig();assert.equal(await audio.play('fireball'),false);assert.equal(await audio.unlock(),true);assert.equal(await audio.play('fireball'),true);assert.equal(starts.length,1);audio.toggle();assert.equal(await audio.play('heal'),false);assert.equal(stops.length,1);audio.toggle();assert.equal(await audio.play('arrows','super'),true);assert.equal(starts.length,4);audio.stop();assert.equal(stops.length,4);});
test('stop cancels pending downloads; load failures do not reject gameplay',async()=>{let resolve;const response=new Promise(r=>resolve=r),{audio,starts}=rig(()=>response);await audio.unlock();const play=audio.play('zap');audio.stop();resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(8)});assert.equal(await play,false);assert.equal(starts.length,0);const fail=rig(async()=>({ok:false}));await fail.audio.unlock();assert.equal(await fail.audio.play('heal'),false);});
test('arrows have staggered impacts and only lingering spells have quiet tick sounds',()=>{assert.equal(new Set(soundCues('arrows','impact').map(c=>c.delay)).size,3);assert.ok(soundCues('poison','tick')[0].gain<.2);assert.ok(soundCues('skeletonArmy','tick')[0].gain<.2);assert.deepEqual(soundCues('fireball','tick'),[]);assert.deepEqual(soundCues('constructor'),[]);});
test('requested consumable clips retain original pitch and full short clip duration',()=>{for(const [spell,length] of [['shield',8],['heal',5],['flashbang',5],['orbital',10]]){const [cue]=soundCues(spell);assert.equal(cue.clip,`${spell}-custom`);assert.equal(cue.rate,1);assert.equal(cue.length,length);}});
test('stopping one strike preserves other spell sounds and cancels pending keyed playback',async()=>{const{audio,starts,stops}=rig();await audio.unlock();await audio.play('orbital','cast',{key:'strike-a'});await audio.play('fireball');audio.stop('strike-a');assert.equal(stops.length,1);audio.stop();assert.equal(stops.length,2);assert.equal(starts.length,2);
let resolve;const response=new Promise(r=>resolve=r),pending=rig(()=>response);await pending.audio.unlock();const playing=pending.audio.play('orbital','cast',{key:'escaped'});pending.audio.stop('escaped');resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(8)});assert.equal(await playing,false);assert.equal(pending.starts.length,0);});
